name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      API_URL: http://localhost:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.PACKAGE_TOKEN}}

      # NestJS Services
      - name: Setup Node.js for NestJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/nestjs/package-lock.json

      - name: Install NestJS dependencies
        run: npm ci
        working-directory: ./backend/nestjs

      - name: Build NestJS Apps
        run: |
          npm run prisma:generate:auth
          npm run prisma:generate:ai-content-service
          npx nest build api-gateway
          npx nest build auth-service
          npx nest build ai-content-service
        working-directory: ./backend/nestjs

      - name: Build and push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./backend/nestjs
          file: ./backend/nestjs/apps/api-gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/snippetquiz-api-gateway:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}/snippetquiz-api-gateway:latest

      - name: Build and push Auth Service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/nestjs
          file: ./backend/nestjs/apps/auth-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/snippetquiz-auth-service:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}/snippetquiz-auth-service:latest

      - name: Build and push AI Content Service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/nestjs
          file: ./backend/nestjs/apps/ai-content-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/snippetquiz-ai-content-service:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}/snippetquiz-ai-content-service:latest

      # Java Core Service
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Java Service
        run: ./gradlew build
        working-directory: ./backend/java

      - name: Build and push Core Service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/java
          file: ./backend/java/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/snippetquiz-core-service:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}/snippetquiz-core-service:latest

      # Frontend
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          build-args: |
            API_URL=http://localhost:5000
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/snippetquiz-frontend:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}/snippetquiz-frontend:latest

      # Create GitHub Release (only for tags)
      - name: Create GitHub Release
        if: steps.version.outputs.is_release == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
