services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d devdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes: 
      - ./local/db:/var/lib/postgresql/data
  
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redispass
    volumes: 
      - ./local/cache:/data

  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    command: npx prisma studio --port 5555 --browser none --schema prisma/db-postgres/schema.prisma 
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

networks:
  default: 
    name: snippetquiz