FROM node:20-alpine

WORKDIR /usr/src/backend

# Instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar código fuente
COPY . .

# Exponer puerto
EXPOSE 3001

# Comando para desarrollo
CMD ["npm", "run", "dev"]