FROM node:20-alpine

WORKDIR /usr/src/backend/nestjs

COPY . .

# Install dependencies first
RUN npm install

# Generate Prisma client
RUN npx prisma generate --schema=prisma/db-postgres/schema.prisma

EXPOSE 6000
