FROM node:20-alpine

WORKDIR /usr/src/backend

COPY ./nestjs ./nestjs

WORKDIR /usr/src/backend/nestjs

COPY package*.json ./

# Generate Prisma client
RUN npx prisma generate --schema=prisma/db-postgres/schema.prisma

RUN npm install

EXPOSE 6000
